# Application Configuration File
# This file contains all configurable settings for the application

# Application settings
app:
  name: "MyApplication"
  version: "1.0.0"
  debug: false
  environment: "development"  # Options: development, staging, production

# Server configuration
server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30
  ssl:
    enabled: false
    cert_file: ""
    key_file: ""

# Database configuration
database:
  # Main database
  main:
    engine: "postgresql"  # Options: postgresql, mysql, sqlite
    host: "localhost"
    port: 5432
    name: "myapp_db"
    user: "myapp_user"
    password: "secure_password"  # Use environment variable in production
    pool_size: 10
    max_overflow: 20
    echo: false  # SQL query logging
  
  # Redis cache configuration
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: ""
    max_connections: 50

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file:
    enabled: true
    path: "logs/app.log"
    max_size: "10MB"
    backup_count: 5
  console:
    enabled: true
    colorize: true

# Security settings
security:
  secret_key: "your-secret-key-here"  # Change in production!
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allow_credentials: true
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allow_headers:
      - "*"

# Email configuration
email:
  enabled: false
  smtp:
    host: "smtp.gmail.com"
    port: 587
    user: "your-email@gmail.com"
    password: "your-app-password"
    use_tls: true
  from_address: "noreply@myapp.com"
  from_name: "MyApp"

# Storage configuration
storage:
  type: "local"  # Options: local, s3, gcs
  local:
    base_path: "uploads/"
    max_file_size: "10MB"
  s3:
    bucket: "my-app-bucket"
    region: "us-east-1"
    access_key: ""
    secret_key: ""
    endpoint_url: ""  # For S3-compatible services

# API configuration
api:
  version: "v1"
  prefix: "/api"
  rate_limit:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000
  pagination:
    default_page_size: 20
    max_page_size: 100

# Feature flags
features:
  registration_enabled: true
  social_auth_enabled: false
  two_factor_auth: false
  api_documentation: true
  maintenance_mode: false

# Third-party services
services:
  stripe:
    enabled: false
    public_key: ""
    secret_key: ""
    webhook_secret: ""
  
  sentry:
    enabled: false
    dsn: ""
    environment: "development"
    traces_sample_rate: 0.1

# Scheduled tasks
tasks:
  cleanup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 30
  
  backup:
    enabled: false
    schedule: "0 3 * * 0"  # Weekly on Sunday at 3 AM
    destination: "backups/"

# Custom application settings
custom:
  # Add your application-specific settings here
  welcome_message: "Welcome to MyApplication!"
  max_upload_size: 5242880  # 5MB in bytes
  supported_file_types:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".pdf"
    - ".doc"
    - ".docx"
