model:
  type: ensemble
  epochs: 10
  batch_size: 32
data:
  source: alpha_vantage
  symbols: ["BTC/USDT", "ETH/USDT", "LTC/USDT", "XRP/USDT"]
environment:
  testnet: false  # Set to true for testnet, false for live
