# ml_config.yaml
model:
  type: ensemble
  algorithms: [xgboost, lightgbm]
  params:
    xgboost:
      learning_rate: 0.05
      max_depth: 7
      n_estimators: 200
    lightgbm:
      learning_rate: 0.03
      num_leaves: 31
      n_estimators: 200
features:
  volatility: 0.3
  volume: 0.2
  sentiment: 0.15
  price_momentum: 0.15
  rsi: 0.1
  macd: 0.1
training:
  validation_split: 0.2
  epochs: 100
  batch_size: 32
